function [X, names] = model_structure_Pw(power, rpm, rpm_dot, model_structure)
    if strcmp(model_structure, 'bem')
        X = [rpm ,...
             power.^(2).*rpm.^(-6), ...
             power.^(3).*rpm.^(-6), ...
             power.^(2).*rpm.^(-5), ...
             rpm.^(2), ...
             power.^(-1).*rpm.^(6)];
        names = {'w', 'p^2*w^-6', 'p^3*w^-6', 'p^2*w^-5', 'w^2', 'p^-1*w^6'};
    
    elseif strcmp(model_structure, 'bem_wdot')
        X = [rpm ,...
             power.^(2).*rpm.^(-6), ...
             power.^(3).*rpm.^(-6), ...
             power.^(2).*rpm.^(-5), ...
             rpm.^(2), ...
             power.^(-1).*rpm.^(6), ...
             rpm.*rpm_dot];
        names = {'w', 'p^2*w^-6', 'p^3*w^-6', 'p^2*w^-5', 'w^2', 'p^-1*w^6', 'w*wdot'};
    
    elseif strcmp(model_structure, 'bem_reduced')
        X = [rpm ,...
             power.^(2).*rpm.^(-5)];
        names = {'w', 'p^2*w^-5'};
    
    elseif strcmp(model_structure, 'bem_reduced_wdot')
        X = [rpm ,...
             power.^(2).*rpm.^(-5), ...
             rpm.*rpm_dot];
        names = {'w', 'p^2*w^-5', 'w*wdot'};
    
    elseif strcmp(model_structure, '144-145-148')
        X = [power.^(-1).*rpm.^5 ,...
             power.^(-1).*rpm.^6, ...
             power.^(1).*rpm.^-3];
        names = {'p^-1*w^5', 'p^-1*w^6', 'p^1*w^-3'};

    elseif strcmp(model_structure, '144-145-148_wdot')
        X = [power.^(-1).*rpm.^5 ,...
             power.^(-1).*rpm.^6, ...
             power.^(1).*rpm.^-3, ...
             rpm.*rpm_dot];
        names = {'p^-1*w^5', 'p^-1*w^6', 'p^1*w^-3', 'w*wdot'};
    
    elseif strcmp(model_structure, 'quadratic')
        X = [power, rpm, ...
             power.^2 , rpm.^2, ...
             power.*rpm];
        names = {'p', 'rpm', 'p^2', 'rpm^2', 'p*rpm'};

    elseif strcmp(model_structure, 'quadratic_wdot')
        X = [power, rpm, ...
             power.^2 , rpm.^2, ...
             power.*rpm, ...
             rpm.*rpm_dot];
        names = {'p', 'rpm', 'p^2', 'rpm^2', 'p*rpm', 'w*wdot'};

    else
        error('Unknown model structure: %s', model_structure);
    end
end